# Hierarchical Models are Exciting



**Welcome to Unit 4 - The final *unit* !**

Hierarchical models for hierarchical (grouped) data

- Chapter 15: Introduce the concepts

- Chapter 16: Hierarchical models without predictors

- Chapter 17: Normal Hierarchical Models with predictors

- Chapter 18: Non-Normal Hierarchical Regression

- Chapter 19: More Layers!


**Chapter 15 - Learning objectives:**

- Explore the limitations of our current Bayesian modeling toolbox under two extremes, complete pooling and no pooling.

- Examine the benefits of the partial pooling provided by hierarchical Bayesian models.

- Focus on the big ideas and leave the details to subsequent chapters.

## Pooled / Grouped data



## Complete Pooling



## Meeting Videos

### Cohort 1

`r knitr::include_url("https://www.youtube.com/embed/URL")`

<details>
<summary> Meeting chat log </summary>

```
LOG
```
</details>

### Cohort 2

`r knitr::include_url("https://www.youtube.com/embed/URL")`

<details>
<summary> Meeting chat log </summary>

```
LOG
```
</details>
