# Adding More Layers

**Learning objectives:**

- THESE ARE NICE TO HAVE BUT NOT ABSOLUTELY NECESSARY

## SLIDE 1

- ADD SLIDES AS SECTIONS (`##`).
- TRY TO KEEP THEM RELATIVELY SLIDE-LIKE; THESE ARE NOTES, NOT THE BOOK ITSELF.


## Further reading

- [Beyond Multiple Linear Regression: Applied Generalized Linear Models and Multilevel Models in R.](https://bookdown.org/roback/bookdown-BeyondMLR/)

    - Julie Legler  and Paul Roback. 2021 A more traditional maxiumun likelyhood approach, but from my scans looks quite thorough. And is free online!

- [Data Analysis Using Regression and Multilevel/Hierarchical Models](http://www.stat.columbia.edu/~gelman/arm/)

    - Andrew Gelman and Jennifer Hill. 2006, Not available for free online, dont know what is in it.


- [Regression and Other Stories](https://avehtari.github.io/ROS-Examples/) 

    - Andrew Gelman, Jennifer Hill, Aki Vehtari 2020
This and the as yet unpublished "Advanced Regression and Multilevel Models" are intended to be the new version of the book mentioned above, as far as I can determine. 

    - Book club starting soon!

## Meeting Videos

### Cohort 1

`r knitr::include_url("https://www.youtube.com/embed/fttQAPfB4Mw")`

<details>
<summary> Meeting chat log </summary>

```
00:13:18	defuneste:	no worries
00:44:06	defuneste:	https://theeffectbook.net/
00:44:26	Brendan Lam:	Looks interesting!
00:47:58	Federica Gazzelloni:	https://www.paulamoraga.com/book-geospatial/
00:48:25	defuneste:	https://www.paulamoraga.com/book-geospatial/
00:49:17	Federica Gazzelloni:	Search: #book_club-geohealth
00:50:50	Brendan Lam:	me too
00:51:49	defuneste:	ROS regression and other stories
```
</details>

### Cohort 2

`r knitr::include_url("https://www.youtube.com/embed/URL")`

<details>
<summary> Meeting chat log </summary>

```
LOG
```
</details>


### Cohort 3

`r knitr::include_url("https://www.youtube.com/embed/URL")`

<details>
<summary> Meeting chat log </summary>

```
LOG
```
</details>
